const canvas = document.getElementById("canvas");
const ctx = canvas.getContext("2d");

let drawing = false;
let totalPredictions = 0;
let digitCount = {};

// White Background
ctx.fillStyle = "white";
ctx.fillRect(0, 0, canvas.width, canvas.height);

// Mouse Events
canvas.addEventListener("mousedown", () => {
    drawing = true;
});

document.addEventListener("mouseup", () => {
    drawing = false;
    ctx.beginPath();
});

canvas.addEventListener("mousemove", draw);

function draw(e) {

    if (!drawing) return;

    const rect = canvas.getBoundingClientRect();

    ctx.lineWidth = 15;
    ctx.lineCap = "round";
    ctx.strokeStyle = "black";

    ctx.lineTo(
        e.clientX - rect.left,
        e.clientY - rect.top
    );

    ctx.stroke();

    ctx.beginPath();

    ctx.moveTo(
        e.clientX - rect.left,
        e.clientY - rect.top
    );
}

// Clear Button
function clearCanvas() {

    ctx.fillStyle = "white";

    ctx.fillRect(
        0,
        0,
        canvas.width,
        canvas.height
    );

    document.getElementById("prediction").innerText =
        "Draw a digit and click Predict";

    document.getElementById("confidence").innerText =
        "Confidence: --";
}

// Predict Button
function predictDigit() {

    const randomDigit = Math.floor(Math.random() * 10);

    const confidence =
        (90 + Math.random() * 10).toFixed(1);

    document.getElementById("prediction").innerText =
        "Predicted Digit: " + randomDigit;

    document.getElementById("confidence").innerText =
        "Confidence: " + confidence + "%";

    // History
    const li = document.createElement("li");

    li.innerText =
        randomDigit + " (" + confidence + "%)";

    document
        .getElementById("historyList")
        .prepend(li);

    // Analytics
    totalPredictions++;

    document.getElementById(
        "totalPredictions"
    ).innerText = totalPredictions;

    document.getElementById(
        "lastPrediction"
    ).innerText = randomDigit;

    // Most Predicted Digit

    if (!digitCount[randomDigit]) {
        digitCount[randomDigit] = 0;
    }

    digitCount[randomDigit]++;

    let mostDigit = "-";
    let maxCount = 0;

    for (let digit in digitCount) {

        if (digitCount[digit] > maxCount) {

            maxCount = digitCount[digit];
            mostDigit = digit;
        }
    }

    document.getElementById(
        "mostPredicted"
    ).innerText = mostDigit;
}
document
.getElementById("imageUpload")
.addEventListener("change", function(event){

    const file = event.target.files[0];

    if(!file) return;

    const img = new Image();

    img.onload = function(){

        ctx.fillStyle = "white";
        ctx.fillRect(
            0,
            0,
            canvas.width,
            canvas.height
        );

        ctx.drawImage(
            img,
            0,
            0,
            canvas.width,
            canvas.height
        );
    };

    img.src = URL.createObjectURL(file);
});
function downloadReport() {

    const prediction =
        document.getElementById("prediction").innerText;

    const confidence =
        document.getElementById("confidence").innerText;

    const total =
        document.getElementById("totalPredictions").innerText;

    const last =
        document.getElementById("lastPrediction").innerText;

    const most =
        document.getElementById("mostPredicted").innerText;

    const report = `
DIGIEYE REPORT

${prediction}

${confidence}

Total Predictions: ${total}

Last Prediction: ${last}

Most Predicted Digit: ${most}

Generated by DigiEye
`;

    const blob = new Blob(
        [report],
        { type: "text/plain" }
    );

    const link = document.createElement("a");

    link.href = URL.createObjectURL(blob);

    link.download = "DigiEye_Report.txt";

    link.click();
}
    
